receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

  # jaeger: 
  #   protocols:
  #     thrift_http:
  #       endpoint: "0.0.0.0:14268"

exporters:
  jaeger:
    endpoint: "collector-elastic:14250"
    tls: 
      insecure: true


processors:
  batch:
  tail_sampling:
    decision_wait: 5s
    num_traces: 100
    expected_new_traces_per_sec: 10
    policies:
      [
          {
            name: policy-status_code,
            type: status_code,
            status_code: {status_codes: [ERROR]}
          },
         {
            name: policy-probabilistic,
            type: probabilistic,
            probabilistic: {sampling_percentage: 10}
         }
      ]
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [jaeger]
