receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

  # jaeger: 
  #   protocols:
  #     thrift_http:
  #       endpoint: "0.0.0.0:14268"

exporters:
  jaeger:
    endpoint: "collector-elastic:14250"
    tls: 
      insecure: true


processors:
  batch:


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
